FROM node:14-alpine

WORKDIR /usr/src/app

COPY /Frontend/kidney-life .
COPY /models/coxnet_deceased_desc.json ./src/models/
COPY /models/coxnet_living_desc.json ./src/models/

RUN npm install

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
