version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./Backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kidneylife_db
      - POSTGRES_USER=user_md
      - POSTGRES_PASSWORD=password
    ports: 
      - "5432:5432"

  web:
    mem_limit: 1g
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
