version: "3.9"
name: kidney-life-dev

services:
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    volumes:
      - ./Backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: 
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - shared_network
    env_file:
      - .dev.env

  web:
    container_name: backend-dev
    mem_limit: 1g
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "${BE_PORT}:${BE_PORT}"
    depends_on:
      - db
    networks:
      - shared_network
    env_file:
      - .dev.env

  frontend:
    container_name: frontend-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "${FE_PORT}:${FE_PORT}"
    networks:
      - shared_network
    depends_on:
      - web
    env_file:
      - .dev.env

networks:
  shared_network:
    driver: bridge 
