FROM node:14-alpine

ARG FE_PORT=3000
# get the port from the environment variable
ENV FE_PORT=$FE_PORT 

WORKDIR /usr/src/app

COPY /Frontend/kidney-life .
COPY /models/*.json ./src/models/

RUN npm install

RUN npm run build

EXPOSE $FE_PORT

CMD ["npm", "start"]
