# syntax=docker/dockerfile:1
FROM continuumio/miniconda3

# Install Python 3.11.5
RUN conda install -y python=3.11.5

RUN apt-get update
RUN apt-get install build-essential -y
RUN apt-get install cmake -y


ENV PYTHONUNBUFFERED=1

WORKDIR /code

# Copy conda requirements file
COPY Backend/environment.yml .

# Create a conda environment and install packages
RUN conda env create -f environment.yml

# Activate the environment
RUN echo "source activate kidney-life" > ~/.bashrc
ENV PATH /opt/conda/envs/myenv/bin:$PATH

# Copy the rest of the project
COPY Backend/ .
COPY models/ ./prediction/models/

CMD ["conda", "run", "--no-capture-output", "-n", "kidney-life", "python", "manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000
