# Generated by Django 4.1 on 2023-12-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="model_description",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
