# Generated by Django 4.1 on 2023-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pair", "0002_rename_donor_id_pair_donor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pair",
            name="id",
        ),
        migrations.AlterField(
            model_name="pair",
            name="pair_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
