# Generated by Django 4.1 on 2023-09-24 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="patient_id",
        ),
    ]
