# Generated by Django 4.1 on 2023-09-25 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0002_remove_donor_patient_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="donor_id",
        ),
    ]
