# Generated by Django 4.1 on 2023-09-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0003_remove_donor_donor_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="donor_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
