# Generated by Django 4.1 on 2023-09-30 09:13

from django.db import migrations


def populate_temp_ids(apps, schema_editor):
    Donor = apps.get_model("donor", "Donor")
    for donor in Donor.objects.all():
        donor.donor_id = donor.id
        donor.save()


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0004_donor_donor_id"),
    ]

    operations = [
        migrations.RunPython(populate_temp_ids),
    ]
