# Generated by Django 4.1 on 2023-09-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0005_auto_20230930_0913"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="donor_id",
            field=models.IntegerField(unique=True),
        ),
    ]
