# Generated by Django 4.1 on 2023-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donor", "0006_alter_donor_donor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="id",
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
