version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kidneylife_db
      - POSTGRES_USER=user_md
      - POSTGRES_PASSWORD=password
    ports: 
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
