name: kidney-life
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - django=4.1
  - djangorestframework=3.14.0
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - tqdm
  - pip
  - psycopg2=2.9.3
  - pip:
    - django-cors-headers==4.2.0
    - django-debug-toolbar==4.2.0
    - ecos
    - joblib
    - osqp
    - scikit-survival==0.22.1
    - python-dotenv
