# Generated by Django 4.1 on 2023-09-25 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipient",
            name="recipient_id",
        ),
    ]
