# Generated by Django 4.1 on 2023-09-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipient", "0002_remove_recipient_recipient_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipient",
            name="recipient_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
