# Generated by Django 4.1 on 2023-09-30 09:28

from django.db import migrations


def populate_temp_ids(apps, schema_editor):
    Recipient = apps.get_model("recipient", "Recipient")
    for recipient in Recipient.objects.all():
        recipient.recipient_id = recipient.id
        recipient.save()


class Migration(migrations.Migration):
    dependencies = [
        ("recipient", "0003_recipient_recipient_id"),
    ]

    operations = [migrations.RunPython(populate_temp_ids)]
