# Generated by Django 4.1 on 2023-09-30 09:35

from django.db import migrations


def populate_temp_ids(apps, schema_editor):
    Recipient = apps.get_model("recipient", "Recipient")
    for recipient in Recipient.objects.all():
        recipient.recipient_id = recipient.id
        recipient.save()


class Migration(migrations.Migration):
    dependencies = [
        ("recipient", "0004_auto_20230930_0928"),
    ]

    operations = [migrations.RunPython(populate_temp_ids)]
