# Generated by Django 4.1 on 2023-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipient", "0005_auto_20230930_0935"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipient",
            name="id",
        ),
        migrations.AlterField(
            model_name="recipient",
            name="recipient_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
